### ISSUE TITLE
SafeArgs and xml graphs?

### ISSUE THREAD

**Issue by P1NG2WIN** [terrakok/Cicerone#125]
Hello. What are you think about integrate your library with Gradle SafeArgs plugin and navigation-like creating graphs from xml? Could this appear in the future? (label:question)

**Comment by P1NG2WIN** [comment]
Or maybe you know some not deprecated articles that will explain how to integrate your library with google navigation?

**Comment by terrakok** [comment]
First of all SafeArgs is not needed because Cicerone uses strong typed Screen classes for navigation hence Kotlin compiler checks it all.
I think that navigation graph may be useful only for small applications with well known static graph.
As I know nav-graph uses documented transition ids instead destination screen for navigation. I'm not sure that it is more usefull than Cicerone style. (But I understand that UI graph representation is cool sometimes)

**Comment by P1NG2WIN** [comment]
> First of all SafeArgs is not needed because Cicerone uses strong typed Screen classes for navigation hence Kotlin compiler checks it all.
> I think that navigation graph may be useful only for small applications with well known static graph.
> As I know nav-graph uses documented transition ids instead destination screen for navigation. I'm not sure that it is more usefull than Cicerone style. (But I understand that UI graph representation is cool sometimes)

Thanks for reply, understand about safe-args. By xml, I meant the ability to see any graph visually, and, possibly, add new destinations to it
