### ISSUE TITLE
Use Cicerone without Moxy

### ISSUE THREAD

**Issue by azurh** [terrakok/Cicerone#34]
Readme says: _"It (Cicerone) was designed to be used with the MVP pattern (try Moxy), but will work great with any architecture."_

Is there any tutorial how to use Cicerone without an MVP architecture? Even the Cicerone library includes Moxy as a dependency. Is there a way to make Cicerone a bit more loosely coupled?

**Comment by Jeevuz** [comment]
Hi! Yep, it can be used with any architecture. And I can't say it coupled to any at all! You can use fragments, conductor's controllers or just views. You can use MVP, MVVM, PM, or any other pattern you want because all you need is to attach Navigator to the Activity, inject Router to needed place and call it's methods there. 
E.g. if you want to just go with Fragments you can inject/get it in your Fragment and use. All will be the same as in MVP sample, but with no presentation pattern used. 

What pattern do you want to use?

**Comment by azurh** [comment]
Hi,
I don't use any pattern currently. I don't have time to mess with patterns for now, since I just want Cicerone to work. 
I have one activity with a navigation drawer, which has list items for 4 other fragments. I'm switching the fragments in a single container and I'm facing known issues with the backstack and screen flow (fragment flow). 
I would like to use Cicerone to do the screen flow work, instead of the built-in backstack and fragment transactions. I found this pretty hard to achieve since some libraries are bundled within the Cicerone examples for getting started.
Please help, thanks.

**Comment by terrakok** [comment]
Hi! Look on this sample class for understanding Navigator:
[MainActivity.java](https://github.com/terrakok/Cicerone/blob/develop/sample/src/main/java/ru/terrakok/cicerone/sample/ui/main/MainActivity.java)

For navigation in your drawer you need execute router.newRootScreen("some screen"):
[Button action](https://github.com/terrakok/Cicerone/blob/develop/sample/src/main/java/ru/terrakok/cicerone/sample/mvp/main/SamplePresenter.java#L51)
