### ISSUE TITLE
Methods showSystemMessage() and exit() not work in Executor

### ISSUE THREAD

**Issue by Z-13** [terrakok/Cicerone#35]
The code sample-cicerone, and change this:
```
public void onForwardWithDelayCommandClick() {
        if (future != null) future.cancel(true);
        future = executorService.schedule(new Runnable() {
            @Override
            public void run() {
             router.showSystemMessage("CHECK");
             router.exit();
             //router.navigateTo(Screens.SAMPLE_SCREEN + (screenNumber + 1), screenNumber + 1);
            }
        }, 5, TimeUnit.SECONDS);
    }
```

Nothing will happen! The methods of the "router" are executed, but no action will occur. And the "navigateTo" method will be executed!

Why do not "exit" and "showSystemMessage" work?

**Comment by Jeevuz** [comment]
This happens because what you are doing is calling thing that cannot be performed **out of the main thread**. We cannot show toast not from ui thread and we cannot call `executePendingTransactions()` which is called inside `popBackStackImmediate()` in the Back() command handling (used for router's exit method) in the navigator.
So the fact is that calling router from the thread other then main is the bad idea.

**Comment by terrakok** [comment]
Yes. Sample has problem. But it only for example ;-)

**Comment by terrakok** [comment]
Thank you for your comment. But I don't think that for a sample this is critical

**Comment by terrakok** [comment]
https://github.com/terrakok/Cicerone/blob/10918fd7590b57f3c1cfe37e5f8cc63c73a3f39d/sample/src/main/java/ru/terrakok/cicerone/sample/mvp/main/SamplePresenter.java#L63
